const HomePage = () => {
  return (
    <div>
      HomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePageHomePage
    </div>
  );
};

export default HomePage;
