export const SERVICE_TYPES = {
  ROOM: "ROOM",
  TOUR: "TOUR",
  TICKET: "TICKET",
  MENU_ITEM: "MENU_ITEM",
};

export const BOOKING_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
};

export const PAYMENT_METHODS = {
  VNPAY: "VNPAY",
  MOMO: "MOMO",
  BLOCKCHAIN: "BLOCKCHAIN",
};
