const { upsertMany } = require("./utils/upsertMany");

const roomFacilities = [
  { room_id: 1, facility_id: 1 },
  { room_id: 1, facility_id: 2 },
  { room_id: 1, facility_id: 3 },
  { room_id: 1, facility_id: 9 },
  { room_id: 1, facility_id: 11 },
  { room_id: 1, facility_id: 13 },

  { room_id: 2, facility_id: 1 },
  { room_id: 2, facility_id: 2 },
  { room_id: 2, facility_id: 3 },
  { room_id: 2, facility_id: 4 },
  { room_id: 2, facility_id: 5 },
  { room_id: 2, facility_id: 9 },
  { room_id: 2, facility_id: 10 },
  { room_id: 2, facility_id: 11 },
  { room_id: 2, facility_id: 12 },
  { room_id: 2, facility_id: 13 },
  { room_id: 2, facility_id: 17 },

  { room_id: 3, facility_id: 1 },
  { room_id: 3, facility_id: 2 },
  { room_id: 3, facility_id: 3 },
  { room_id: 3, facility_id: 4 },
  { room_id: 3, facility_id: 5 },
  { room_id: 3, facility_id: 6 },
  { room_id: 3, facility_id: 9 },
  { room_id: 3, facility_id: 10 },
  { room_id: 3, facility_id: 11 },
  { room_id: 3, facility_id: 12 },
  { room_id: 3, facility_id: 13 },
  { room_id: 3, facility_id: 14 },
  { room_id: 3, facility_id: 17 },

  { room_id: 4, facility_id: 1 },
  { room_id: 4, facility_id: 2 },
  { room_id: 4, facility_id: 3 },
  { room_id: 4, facility_id: 9 },
  { room_id: 4, facility_id: 11 },

  { room_id: 5, facility_id: 1 },
  { room_id: 5, facility_id: 2 },
  { room_id: 5, facility_id: 3 },
  { room_id: 5, facility_id: 6 },
  { room_id: 5, facility_id: 7 },
  { room_id: 5, facility_id: 9 },
  { room_id: 5, facility_id: 10 },
  { room_id: 5, facility_id: 12 },

  { room_id: 6, facility_id: 1 },
  { room_id: 6, facility_id: 2 },
  { room_id: 6, facility_id: 3 },
  { room_id: 6, facility_id: 4 },
  { room_id: 6, facility_id: 5 },
  { room_id: 6, facility_id: 6 },
  { room_id: 6, facility_id: 7 },
  { room_id: 6, facility_id: 9 },
  { room_id: 6, facility_id: 10 },
  { room_id: 6, facility_id: 12 },

  { room_id: 7, facility_id: 1 },
  { room_id: 7, facility_id: 2 },
  { room_id: 7, facility_id: 3 },
  { room_id: 7, facility_id: 9 },
  { room_id: 7, facility_id: 10 },
  { room_id: 7, facility_id: 11 },

  { room_id: 8, facility_id: 1 },
  { room_id: 8, facility_id: 2 },
  { room_id: 8, facility_id: 3 },
  { room_id: 8, facility_id: 6 },
  { room_id: 8, facility_id: 7 },
  { room_id: 8, facility_id: 9 },
  { room_id: 8, facility_id: 12 },

  { room_id: 9, facility_id: 1 },
  { room_id: 9, facility_id: 2 },
  { room_id: 9, facility_id: 3 },
  { room_id: 9, facility_id: 9 },
  { room_id: 9, facility_id: 11 },

  { room_id: 10, facility_id: 1 },
  { room_id: 10, facility_id: 2 },
  { room_id: 10, facility_id: 3 },
  { room_id: 10, facility_id: 6 },
  { room_id: 10, facility_id: 9 },
  { room_id: 10, facility_id: 11 },
  { room_id: 10, facility_id: 12 },

  { room_id: 11, facility_id: 1 },
  { room_id: 11, facility_id: 2 },
  { room_id: 11, facility_id: 3 },
  { room_id: 11, facility_id: 9 },
  { room_id: 11, facility_id: 11 },
  { room_id: 11, facility_id: 12 },

  { room_id: 12, facility_id: 1 },
  { room_id: 12, facility_id: 2 },
  { room_id: 12, facility_id: 3 },
  { room_id: 12, facility_id: 6 },
  { room_id: 12, facility_id: 9 },
  { room_id: 12, facility_id: 10 },
  { room_id: 12, facility_id: 11 },
  { room_id: 12, facility_id: 12 },

  { room_id: 13, facility_id: 1 },
  { room_id: 13, facility_id: 2 },
  { room_id: 13, facility_id: 3 },
  { room_id: 13, facility_id: 9 },
  { room_id: 13, facility_id: 11 },

  { room_id: 14, facility_id: 1 },
  { room_id: 14, facility_id: 2 },
  { room_id: 14, facility_id: 3 },
  { room_id: 14, facility_id: 8 },
  { room_id: 14, facility_id: 9 },
  { room_id: 14, facility_id: 11 },
  { room_id: 14, facility_id: 12 },

  { room_id: 15, facility_id: 1 },
  { room_id: 15, facility_id: 2 },
  { room_id: 15, facility_id: 3 },
  { room_id: 15, facility_id: 4 },
  { room_id: 15, facility_id: 6 },
  { room_id: 15, facility_id: 8 },
  { room_id: 15, facility_id: 9 },
  { room_id: 15, facility_id: 10 },
  { room_id: 15, facility_id: 11 },
  { room_id: 15, facility_id: 12 },

  { room_id: 16, facility_id: 1 },
  { room_id: 16, facility_id: 2 },
  { room_id: 16, facility_id: 3 },
  { room_id: 16, facility_id: 8 },
  { room_id: 16, facility_id: 9 },
  { room_id: 16, facility_id: 11 },
  { room_id: 16, facility_id: 12 },

  { room_id: 17, facility_id: 1 },
  { room_id: 17, facility_id: 2 },
  { room_id: 17, facility_id: 3 },
  { room_id: 17, facility_id: 9 },
  { room_id: 17, facility_id: 11 },

  { room_id: 18, facility_id: 1 },
  { room_id: 18, facility_id: 2 },
  { room_id: 18, facility_id: 3 },
  { room_id: 18, facility_id: 9 },
  { room_id: 18, facility_id: 11 },
  { room_id: 18, facility_id: 12 },
  { room_id: 18, facility_id: 13 },

  { room_id: 19, facility_id: 1 },
  { room_id: 19, facility_id: 2 },
  { room_id: 19, facility_id: 3 },
  { room_id: 19, facility_id: 9 },
  { room_id: 19, facility_id: 11 },
  { room_id: 19, facility_id: 12 },
  { room_id: 19, facility_id: 13 },

  { room_id: 20, facility_id: 1 },
  { room_id: 20, facility_id: 2 },
  { room_id: 20, facility_id: 3 },
  { room_id: 20, facility_id: 4 },
  { room_id: 20, facility_id: 5 },
  { room_id: 20, facility_id: 6 },
  { room_id: 20, facility_id: 9 },
  { room_id: 20, facility_id: 10 },
  { room_id: 20, facility_id: 11 },
  { room_id: 20, facility_id: 12 },
  { room_id: 20, facility_id: 13 },
];

async function seedRoomFacilities(prisma) {
  console.log("Seeding room facilities...");
  await upsertMany(prisma, prisma.roomFacility, roomFacilities, ["room_id", "facility_id"]);
  console.log(`Seeded ${roomFacilities.length} room facility associations`);
}

module.exports = { seedRoomFacilities };
