const { upsertMany } = require("./utils/upsertMany");

const rooms = [
  // Sunrise Grand Hotel (service_id: 1)
  {
    id: 1,
    service_id: 1,
    name: "Deluxe City View",
    description: "Spacious room with panoramic city views",
    price_per_night: 120.0,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    id: 2,
    service_id: 1,
    name: "Executive Suite",
    description: "Luxurious suite with separate living area",
    price_per_night: 250.0,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: false,
    bed_number: 2,
  },
  {
    id: 3,
    service_id: 1,
    name: "Presidential Suite",
    description: "Ultimate luxury with private balcony and butler service",
    price_per_night: 500.0,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },
  {
    id: 4,
    service_id: 1,
    name: "Superior Twin",
    description: "Comfortable room with two single beds",
    price_per_night: 100.0,
    max_children_number: 1,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 2,
  },

  // Sunrise Beach Resort (service_id: 2)
  {
    id: 5,
    service_id: 2,
    name: "Ocean View Bungalow",
    description: "Private bungalow steps from the beach",
    price_per_night: 180.0,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: true,
    bed_number: 1,
  },
  {
    id: 6,
    service_id: 2,
    name: "Beach Villa",
    description: "Luxury villa with private pool and beach access",
    price_per_night: 400.0,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },
  {
    id: 7,
    service_id: 2,
    name: "Garden Suite",
    description: "Tropical garden view with outdoor shower",
    price_per_night: 150.0,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    id: 8,
    service_id: 2,
    name: "Family Cottage",
    description: "Spacious cottage perfect for families",
    price_per_night: 220.0,
    max_children_number: 4,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },

  // Sunrise Boutique Hotel (service_id: 3)
  {
    id: 9,
    service_id: 3,
    name: "Heritage Room",
    description: "Traditional Vietnamese design with modern comfort",
    price_per_night: 80.0,
    max_children_number: 1,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    id: 10,
    service_id: 3,
    name: "Deluxe Heritage",
    description: "Larger heritage room with balcony",
    price_per_night: 110.0,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    id: 11,
    service_id: 3,
    name: "Family Suite",
    description: "Two-bedroom suite with living area",
    price_per_night: 180.0,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },
  {
    id: 12,
    service_id: 3,
    name: "Rooftop Loft",
    description: "Unique loft with private terrace",
    price_per_night: 200.0,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },

  // Sunrise Mountain Lodge (service_id: 4)
  {
    id: 13,
    service_id: 4,
    name: "Valley View Room",
    description: "Cozy room with stunning valley views",
    price_per_night: 70.0,
    max_children_number: 1,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    id: 14,
    service_id: 4,
    name: "Mountain Cabin",
    description: "Rustic cabin with fireplace",
    price_per_night: 120.0,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },
  {
    id: 15,
    service_id: 4,
    name: "Luxury Mountain Suite",
    description: "Premium suite with panoramic windows",
    price_per_night: 180.0,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },
  {
    id: 16,
    service_id: 4,
    name: "Family Lodge",
    description: "Large lodge for family gatherings",
    price_per_night: 250.0,
    max_children_number: 4,
    max_adult_number: 5,
    pet_allowed: true,
    bed_number: 4,
  },

  // Sunrise City Apartments (service_id: 5)
  {
    id: 17,
    service_id: 5,
    name: "Studio Apartment",
    description: "Modern studio with kitchenette",
    price_per_night: 60.0,
    max_children_number: 1,
    max_adult_number: 2,
    pet_allowed: true,
    bed_number: 1,
  },
  {
    id: 18,
    service_id: 5,
    name: "One Bedroom Apartment",
    description: "Fully equipped apartment with living room",
    price_per_night: 90.0,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },
  {
    id: 19,
    service_id: 5,
    name: "Two Bedroom Apartment",
    description: "Spacious apartment ideal for families",
    price_per_night: 130.0,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },
  {
    id: 20,
    service_id: 5,
    name: "Penthouse",
    description: "Luxury penthouse with city views",
    price_per_night: 280.0,
    max_children_number: 3,
    max_adult_number: 5,
    pet_allowed: true,
    bed_number: 4,
  },
];

async function seedRooms(prisma) {
  console.log("Seeding rooms...");
  await upsertMany(prisma, prisma.room, rooms, ["id"]);
  console.log(`Seeded ${rooms.length} rooms`);
}

module.exports = { seedRooms };
