const { upsertMany } = require("./utils/upsertMany");

const rooms = [
  // ========== Service ID 1: Khách Sạn Sunrise Grand ==========
  {
    service_id: 1,
    name: "Phòng Deluxe View Thành Phố",
    description: "Phòng rộng rãi với view toàn cảnh thành phố",
    price_per_night: 1200000,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    service_id: 1,
    name: "Phòng Hành Động Điều Hành",
    description: "Suite sang trọng với phòng khách riêng biệt",
    price_per_night: 2500000,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: false,
    bed_number: 2,
  },
  {
    service_id: 1,
    name: "Phòng Presidential Suite",
    description: "Phòng cao cấp nhất với ban công riêng và dịch vụ butler",
    price_per_night: 5000000,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },
  {
    service_id: 1,
    name: "Phòng Superior Twin",
    description: "Phòng thoải mái với hai giường đơn",
    price_per_night: 1000000,
    max_children_number: 1,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 2,
  },

  // ========== Service ID 2: Resort Bãi Biển Sunrise ==========
  {
    service_id: 2,
    name: "Bungalow View Biển",
    description: "Bungalow riêng tư sát bãi biển",
    price_per_night: 1800000,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: true,
    bed_number: 1,
  },
  {
    service_id: 2,
    name: "Villa Bãi Biển",
    description: "Villa sang trọng với bể bơi riêng và bãi biển",
    price_per_night: 4000000,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },
  {
    service_id: 2,
    name: "Suite View Vườn",
    description: "View vườn nhiệt đới với vòi sen ngoài trời",
    price_per_night: 1500000,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    service_id: 2,
    name: "Cottage Gia Đình",
    description: "Cottage rộng rãi hoàn hảo cho gia đình",
    price_per_night: 2200000,
    max_children_number: 4,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },

  // ========== Service ID 3: Khách Sạn Boutique Sunrise ==========
  {
    service_id: 3,
    name: "Phòng Di Sản",
    description: "Thiết kế Việt Nam truyền thống với tiện nghi hiện đại",
    price_per_night: 800000,
    max_children_number: 1,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    service_id: 3,
    name: "Phòng Deluxe Di Sản",
    description: "Phòng di sản lớn hơn với ban công",
    price_per_night: 1100000,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    service_id: 3,
    name: "Suite Gia Đình",
    description: "Suite hai phòng ngủ với phòng khách",
    price_per_night: 1800000,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },
  {
    service_id: 3,
    name: "Loft Trên Mái",
    description: "Loft độc đáo với sân thượng riêng",
    price_per_night: 2000000,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },

  // ========== Service ID 4: Lều Núi Sunrise ==========
  {
    service_id: 4,
    name: "Phòng View Thung Lũng",
    description: "Phòng ấm cúng với view thung lũng tuyệt đẹp",
    price_per_night: 700000,
    max_children_number: 1,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    service_id: 4,
    name: "Cabin Núi",
    description: "Cabin mộc mạc với lò sưởi",
    price_per_night: 1200000,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },
  {
    service_id: 4,
    name: "Suite Núi Hạng Sang",
    description: "Suite cao cấp với cửa sổ toàn cảnh",
    price_per_night: 1800000,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },
  {
    service_id: 4,
    name: "Lodge Gia Đình",
    description: "Lodge lớn cho tập hợp gia đình",
    price_per_night: 2500000,
    max_children_number: 4,
    max_adult_number: 5,
    pet_allowed: true,
    bed_number: 4,
  },

  // ========== Service ID 5: Căn Hộ Phục Vụ Sunrise ==========
  {
    service_id: 5,
    name: "Studio Apartment",
    description: "Studio hiện đại với bếp nấu nhỏ",
    price_per_night: 600000,
    max_children_number: 1,
    max_adult_number: 2,
    pet_allowed: true,
    bed_number: 1,
  },
  {
    service_id: 5,
    name: "Căn Hộ Một Phòng",
    description: "Căn hộ được trang bị đầy đủ với phòng khách",
    price_per_night: 900000,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },
  {
    service_id: 5,
    name: "Căn Hộ Hai Phòng",
    description: "Căn hộ rộng rãi lý tưởng cho gia đình",
    price_per_night: 1300000,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 3,
  },

  // ========== Service ID 6: Resort Hạ Long ==========
  {
    service_id: 6,
    name: "Phòng View Vịnh",
    description: "Phòng với view vịnh Hạ Long đẹp",
    price_per_night: 1500000,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    service_id: 6,
    name: "Suite Hạ Long",
    description: "Suite sang trọng với ban công riêng",
    price_per_night: 2800000,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 2,
  },
  {
    service_id: 6,
    name: "Phòng Gia Đình Hạ Long",
    description: "Phòng rộng cho gia đình nhỏ",
    price_per_night: 2000000,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: false,
    bed_number: 2,
  },

  // ========== Service ID 7: Khách Sạn Nha Trang ==========
  {
    service_id: 7,
    name: "Phòng Biển Nha Trang",
    description: "Phòng với view biển và bãi cát trắng",
    price_per_night: 1200000,
    max_children_number: 2,
    max_adult_number: 2,
    pet_allowed: false,
    bed_number: 1,
  },
  {
    service_id: 7,
    name: "Suite Nha Trang",
    description: "Suite với ban công facing biển",
    price_per_night: 2400000,
    max_children_number: 2,
    max_adult_number: 3,
    pet_allowed: true,
    bed_number: 2,
  },
  {
    service_id: 7,
    name: "Bungalow Biển Nha Trang",
    description: "Bungalow sát bãi biển Nha Trang",
    price_per_night: 2000000,
    max_children_number: 3,
    max_adult_number: 4,
    pet_allowed: true,
    bed_number: 2,
  },
];

async function seedRooms(prisma) {
  console.log("Seeding rooms...");
  await upsertMany(prisma, prisma.room, rooms, ["service_id", "name"]);
  console.log(`Seeded ${rooms.length} rooms`);
}

module.exports = { seedRooms };
