const { upsertMany } = require("./utils/upsertMany");

const tours = [
  {
    id: 1,
    name: "Mekong Delta Full Day Discovery",
    description: "Comprehensive tour of floating markets, villages, and traditional crafts",
    service_price: 850000,
    total_price: 1200000,
    duration: 8,
    is_recurring: true,
    repeat_rule: "daily",
    repeat_days: [],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 11,
    tourguide_id: 1,
  },
  {
    id: 2,
    name: "Sunset River Cruise",
    description: "Romantic evening cruise with dinner on the Mekong River",
    service_price: 650000,
    total_price: 900000,
    duration: 3,
    is_recurring: true,
    repeat_rule: "daily",
    repeat_days: [],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 12,
    tourguide_id: 2,
  },
  {
    id: 3,
    name: "Cycling Village Tour",
    description: "Explore rural life by bicycle with stops at local homes",
    service_price: 450000,
    total_price: 600000,
    duration: 4,
    is_recurring: true,
    repeat_rule: "weekly",
    repeat_days: ["monday", "wednesday", "friday", "saturday"],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 13,
    tourguide_id: 3,
  },
  {
    id: 4,
    name: "Sam Mountain Spiritual Journey",
    description: "Visit temples and pagodas on sacred Sam Mountain",
    service_price: 380000,
    total_price: 550000,
    duration: 5,
    is_recurring: true,
    repeat_rule: "daily",
    repeat_days: [],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 14,
    tourguide_id: 1,
  },
  {
    id: 5,
    name: "Tra Su Forest Eco Tour",
    description: "Bird watching and nature exploration in cajuput forest",
    service_price: 520000,
    total_price: 750000,
    duration: 6,
    is_recurring: true,
    repeat_rule: "weekly",
    repeat_days: ["tuesday", "thursday", "saturday", "sunday"],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 15,
    tourguide_id: 4,
  },
  {
    id: 6,
    name: "Floating Market Morning Tour",
    description: "Early morning visit to bustling Cai Rang floating market",
    service_price: 420000,
    total_price: 580000,
    duration: 4,
    is_recurring: true,
    repeat_rule: "daily",
    repeat_days: [],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 11,
    tourguide_id: 2,
  },
  {
    id: 7,
    name: "Culinary Adventure Tour",
    description: "Food tasting tour through local markets and restaurants",
    service_price: 550000,
    total_price: 800000,
    duration: 5,
    is_recurring: true,
    repeat_rule: "weekly",
    repeat_days: ["friday", "saturday", "sunday"],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 11, // fix typo 'sService' → 'service_id'
    tourguide_id: 5,
  },
  {
    id: 8,
    name: "Floating Village Experience",
    description: "Visit fish farms and floating houses on the river",
    service_price: 380000,
    total_price: 520000,
    duration: 3,
    is_recurring: true,
    repeat_rule: "daily",
    repeat_days: [],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 11,
    tourguide_id: 3,
  },
  {
    id: 9,
    name: "Two-Day Mekong Explorer",
    description: "Extended tour covering multiple provinces with homestay",
    service_price: 1800000,
    total_price: 2500000,
    duration: 16,
    is_recurring: false,
    repeat_rule: null,
    repeat_days: [],
    start_date: new Date("2025-11-15"),
    end_date: new Date("2025-11-16"),
    status: "AVAILABLE",
    service_id: 11,
    tourguide_id: 1,
  },
  {
    id: 10,
    name: "Photography Tour",
    description: "Capture the beauty of Mekong Delta with expert guidance",
    service_price: 680000,
    total_price: 950000,
    duration: 6,
    is_recurring: true,
    repeat_rule: "weekly",
    repeat_days: ["saturday", "sunday"],
    start_date: null,
    end_date: null,
    status: "AVAILABLE",
    service_id: 11,
    tourguide_id: 4,
  },
];

async function seedTours(prisma) {
  console.log("Seeding tours...");

  await upsertMany(prisma, prisma.tour, tours, ["id"]);
  console.log(`Seeded ${tours.length} tours`);
}

module.exports = { seedTours };
