#!/bin/sh

# Chạy lint-staged cho backend
cd $(git rev-parse --show-toplevel)/backend && npx lint-staged || exit 1

# Chạy lint-staged cho frontend
cd $(git rev-parse --show-toplevel)/frontend && npx lint-staged || exit 1
