#!/bin/sh
echo "Starting backend lint" >> $(git rev-parse --show-toplevel)/hook.log
cd $(git rev-parse --show-toplevel)/backend && npx lint-staged || { echo "Backend failed" >> $(git rev-parse --show-toplevel)/hook.log; exit 1; }
echo "Starting frontend lint" >> $(git rev-parse --show-toplevel)/hook.log
cd $(git rev-parse --show-toplevel)/frontend && npx lint-staged || { echo "Frontend failed" >> $(git rev-parse --show-toplevel)/hook.log; exit 1; }
