#!/bin/sh
echo "Starting backend lint" >> hook.log
cd backend && npx lint-staged || { echo "Backend failed" >> hook.log; exit 1; }
echo "Starting frontend lint" >> hook.log
cd ../frontend && npx lint-staged || { echo "Frontend failed" >> hook.log; exit 1; }
