#!/bin/sh
echo "Starting backend lint"
cd backend && npx lint-staged || { echo "Backend failed"; exit 1; }
echo "Starting frontend lint"
cd ../frontend && npx lint-staged || { echo "Frontend failed"; exit 1; }
